{
    "openapi": "3.0.0",
    "info": {
        "title": "",
        "description": "",
        "contact": {
            "email": "projetos.r@hotmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3003/",
            "description": "API-Dev"
        },
        {
            "url": "https://desafiotrademaster.herokuapp.com",
            "description": "API-Prod"
        }
    ],
    "paths": {
        "/entertainment/create": {
            "post": {
                "sumary": "Cadastro de entretenimentos",
                "description": "Essa rota será responsável por cadastrar um novo entretenimento",
                "tags": ["Entertainment"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Entertainment"
                            },
                            "examples": {
                                "entertainment": {
                                    "value": {
                                        "name": "Homem Aranha",
                                        "entertainmentType_Id": 1,
                                        "entertainmentStatus_Id": 1,
                                        "user": "",
                                        "rentDays": 0
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Sucess",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Entertainment"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Inertanl Server Error"
                    }
                }
            }
        },
        "/entertainment/rentOrSaler": {
            "post": {
                "sumary": "Retorna os entretenimento",
                "description": "Essa rota será responsável por registrar se o entretenimento está alugado, vendas ou ambos",
                "tags": ["Entertainment"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/EntertainmentOrder"
                            },
                            "examples": {
                                "entertainment": {
                                    "value": {
                                        "entertainment_Id": 1,
                                        "entertainmentStatus_Id": 1,
                                        "rentDays": 5,
                                        "user": "robson teste",
                                        "active": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Entertainment"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/entertainment/all": {
            "get": {
                "sumary": "Retorna todos os entretenimentos",
                "description": "Essa rota será responsável por retornar todos os entretenimento",
                "tags": ["Entertainment"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Entertainment"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/entertainment/findByParams?name={name}&type={type}": {
            "get": {
                "sumary": "Retorna os entretenimento",
                "description": "Essa rota será responsável por efetuar a busca por nome ou tipo",
                "tags": ["Entertainment"],
                "parameters": [
                    {
                        "in": "query",
                        "name": "name",
                        "requered": "true",
                        "type": "string"
                    },
                    {
                        "in": "query",
                        "name": "type",
                        "requered": "true",
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Entertainment"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/entertainment/edit/{id}": {
            "put": {
                "sumary": "Retorna os entretenimento",
                "description": "Essa rota será responsável por editar um entretenimento ",
                "tags": ["Entertainment"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "requered": "true",
                        "type": "number"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Entertainment"
                            },
                            "examples": {
                                "entertainment": {
                                    "value": {
                                        "name": "Homem Aranha",
                                        "entertainment_Id": 1,
                                        "entertainmentStatus_Id": 1,
                                        "user": "",
                                        "rentDays": 0
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Entertainment"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/entertainment/delete/{id}": {
            "delete": {
                "sumary": "Retorna os entretenimento",
                "description": "Essa rota será responsável por deletar um entretenimento",
                "tags": ["Entertainment"],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": "true",
                        "type": "number"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sucess",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Entertainment"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/entertainmentTypes/all": {
            "get": {
                "sumary": "Retorna os entretenimento",
                "description": "Essa rota será responsável todos os tipos",
                "tags": ["EntertainmentTypes"],
                "responses": {
                    "200": {
                        "description": "Sucess",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/EntertainmentTypes"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/entertainmentStatus/all": {
            "get": {
                "sumary": "Retorna os entretenimento",
                "description": "Essa rota será responsável por retornar todos status",
                "tags": ["EntertainmentStatus"],
                "responses": {
                    "200": {
                        "description": "Sucess",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/EntertainmentStatus"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/entertainmentOrder/all": {
            "get": {
                "sumary": "Retorna todos os entretenimentos",
                "description": "Essa rota será responsável por retornar todos as ordem criada",
                "tags": ["EntertainmentOrder"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "aplication/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/EntertainmentOrder"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Entertainment": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "entertainmentType_Id": {
                        "type": "number"
                    },
                    "entertainmentStatus_Id": {
                        "type": "number"
                    },
                    "user": {
                        "type": "number"
                    },
                    "active": {
                        "type": "number"
                    }
                },
                "required": ["name", "entertainmentType_Id", "entertainmentStatus_Id", "user"]
            },
            "EntertainmentStatus": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "description": {
                        "type": "string"
                    }
                }
            },
            "EntertainmentTypes": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "description": {
                        "type": "string"
                    }
                },
                "required": ["description"]
            },
            "EntertainmentOrder": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "entertainment_Id": {
                        "type": "number"
                    },
                    "entertainmentStatus_Id": {
                        "type": "number"
                    },
                    "rentDays": {
                        "type": "number",
                        "description": "Se entertainmentStatus_Id = 1 deve ser informado rentDays > 0 "
                    },
                    "user": {
                        "type": "string"
                    },
                    "dataPrevision": {
                        "type": "Date"
                    },
                    "active": {
                        "type": "number"
                    }
                },
                "required": ["entertainment_Id", "entertainmentStatus_Id", "rentDays", "user"]
            }
        }
    }
}
